// Hide unused AllTheOres materials.

const retiredAllTheOresItems = [
    "create:crushed_raw_platinum",
    "alltheores:cinnabar",
    "alltheores:cinnabar_block",
    "alltheores:cinnabar_dust",
    "alltheores:cinnabar_ore",
    "alltheores:deepslate_cinnabar_ore",
    "alltheores:deepslate_iridium_ore",
    "alltheores:deepslate_peridot_ore",
    "alltheores:deepslate_platinum_ore",
    "alltheores:deepslate_ruby_ore",
    "alltheores:deepslate_sapphire_ore",
    "alltheores:end_cinnabar_ore",
    "alltheores:end_iridium_ore",
    "alltheores:end_peridot_ore",
    "alltheores:end_platinum_ore",
    "alltheores:end_ruby_ore",
    "alltheores:end_sapphire_ore",
    "alltheores:enderium_block",
    "alltheores:enderium_dust",
    "alltheores:enderium_gear",
    "alltheores:enderium_ingot",
    "alltheores:enderium_nugget",
    "alltheores:enderium_plate",
    "alltheores:enderium_rod",
    "alltheores:iridium_block",
    "alltheores:iridium_clump",
    "alltheores:iridium_crystal",
    "alltheores:iridium_dust",
    "alltheores:iridium_gear",
    "alltheores:iridium_ingot",
    "alltheores:iridium_nugget",
    "alltheores:iridium_ore",
    "alltheores:iridium_plate",
    "alltheores:iridium_rod",
    "alltheores:iridium_shard",
    "alltheores:lumium_block",
    "alltheores:lumium_dust",
    "alltheores:lumium_gear",
    "alltheores:lumium_ingot",
    "alltheores:lumium_nugget",
    "alltheores:lumium_plate",
    "alltheores:lumium_rod",
    "alltheores:molten_enderium_bucket",
    "alltheores:molten_iridium_bucket",
    "alltheores:molten_lumium_bucket",
    "alltheores:molten_platinum_bucket",
    "alltheores:molten_signalum_bucket",
    "alltheores:nether_cinnabar_ore",
    "alltheores:nether_iridium_ore",
    "alltheores:nether_peridot_ore",
    "alltheores:nether_platinum_ore",
    "alltheores:nether_ruby_ore",
    "alltheores:nether_sapphire_ore",
    "alltheores:other_cinnabar_ore",
    "alltheores:other_iridium_ore",
    "alltheores:other_peridot_ore",
    "alltheores:other_platinum_ore",
    "alltheores:other_ruby_ore",
    "alltheores:other_sapphire_ore",
    "alltheores:peridot",
    "alltheores:peridot_block",
    "alltheores:peridot_dust",
    "alltheores:peridot_ore",
    "alltheores:platinum_block",
    "alltheores:platinum_clump",
    "alltheores:platinum_crystal",
    "alltheores:platinum_dust",
    "alltheores:platinum_gear",
    "alltheores:platinum_ingot",
    "alltheores:platinum_nugget",
    "alltheores:platinum_ore",
    "alltheores:platinum_ore_hammer",
    "alltheores:platinum_plate",
    "alltheores:platinum_rod",
    "alltheores:platinum_shard",
    "alltheores:raw_iridium",
    "alltheores:raw_iridium_block",
    "alltheores:raw_platinum",
    "alltheores:raw_platinum_block",
    "alltheores:ruby",
    "alltheores:ruby_block",
    "alltheores:ruby_dust",
    "alltheores:ruby_ore",
    "alltheores:sapphire",
    "alltheores:sapphire_block",
    "alltheores:sapphire_dust",
    "alltheores:sapphire_ore",
    "alltheores:signalum_block",
    "alltheores:signalum_dust",
    "alltheores:signalum_gear",
    "alltheores:signalum_ingot",
    "alltheores:signalum_nugget",
    "alltheores:signalum_plate",
    "alltheores:signalum_rod"
]

const retiredAllTheOresFluids = [
    "alltheores:molten_enderium",
    "alltheores:molten_iridium",
    "alltheores:molten_lumium",
    "alltheores:molten_platinum",
    "alltheores:molten_signalum"
]

RecipeViewerEvents.removeEntriesCompletely('item', event => {
    retiredAllTheOresItems.forEach(id => {
        event.remove(id)
    })
})

RecipeViewerEvents.removeEntriesCompletely('fluid', event => {
    retiredAllTheOresFluids.forEach(id => {
        event.remove(id)
    })
})
