// Removes AllTheOres materials
// Also removes duplicate ore-processing recipes shared with the Ancient Stone / Mekanism compat cleanup below
const removedAllTheOresRecipes = [
    "ae2:matter_cannon/nuggets/iridium",
    "ae2:matter_cannon/nuggets/platinum",
    "allthecompressed:compress/cinnabar_block_1x",
    "allthecompressed:compress/enderium_block_1x",
    "allthecompressed:compress/iridium_block_1x",
    "allthecompressed:compress/lumium_block_1x",
    "allthecompressed:compress/peridot_block_1x",
    "allthecompressed:compress/platinum_block_1x",
    "allthecompressed:compress/raw_iridium_block_1x",
    "allthecompressed:compress/raw_platinum_block_1x",
    "allthecompressed:compress/ruby_block_1x",
    "allthecompressed:compress/sapphire_block_1x",
    "allthecompressed:compress/signalum_block_1x",
    "allthecompressed:decompress/cinnabar_block_1x",
    "allthecompressed:decompress/enderium_block_1x",
    "allthecompressed:decompress/iridium_block_1x",
    "allthecompressed:decompress/lumium_block_1x",
    "allthecompressed:decompress/peridot_block_1x",
    "allthecompressed:decompress/platinum_block_1x",
    "allthecompressed:decompress/raw_iridium_block_1x",
    "allthecompressed:decompress/raw_platinum_block_1x",
    "allthecompressed:decompress/ruby_block_1x",
    "allthecompressed:decompress/sapphire_block_1x",
    "allthecompressed:decompress/signalum_block_1x",
    "alltheores:alloy_smelting/enderium_ingot",
    "alltheores:alloy_smelting/lumium_ingot",
    "alltheores:alloy_smelting/signalum_ingot",
    "alltheores:arcfurnace/enderium/from_dust",
    "alltheores:arcfurnace/enderium/from_gear",
    "alltheores:arcfurnace/enderium/from_plate",
    "alltheores:arcfurnace/enderium/from_rod",
    "alltheores:arcfurnace/enderium/ingot",
    "alltheores:arcfurnace/iridium/from_dust",
    "alltheores:arcfurnace/iridium/from_gear",
    "alltheores:arcfurnace/iridium/from_plate",
    "alltheores:arcfurnace/iridium/from_raw",
    "alltheores:arcfurnace/iridium/from_raw_block",
    "alltheores:arcfurnace/iridium/from_rod",
    "alltheores:arcfurnace/lumium/from_dust",
    "alltheores:arcfurnace/lumium/from_gear",
    "alltheores:arcfurnace/lumium/from_plate",
    "alltheores:arcfurnace/lumium/from_rod",
    "alltheores:arcfurnace/lumium/ingot",
    "alltheores:arcfurnace/platinum/from_dust",
    "alltheores:arcfurnace/platinum/from_gear",
    "alltheores:arcfurnace/platinum/from_plate",
    "alltheores:arcfurnace/platinum/from_raw",
    "alltheores:arcfurnace/platinum/from_raw_block",
    "alltheores:arcfurnace/platinum/from_rod",
    "alltheores:arcfurnace/signalum/from_dust",
    "alltheores:arcfurnace/signalum/from_gear",
    "alltheores:arcfurnace/signalum/from_plate",
    "alltheores:arcfurnace/signalum/from_rod",
    "alltheores:arcfurnace/signalum/ingot",
    "alltheores:crafting/cinnabar/block_from_gem",
    "alltheores:crafting/cinnabar/gem_from_block",
    "alltheores:crafting/enderium/alloy_blending_from_dust",
    "alltheores:crafting/enderium/block_from_ingot",
    "alltheores:crafting/enderium/gear",
    "alltheores:crafting/enderium/ingot_from_block",
    "alltheores:crafting/enderium/ingot_from_nugget",
    "alltheores:crafting/enderium/nugget_from_ingot",
    "alltheores:crafting/enderium/plate",
    "alltheores:crafting/enderium/rod",
    "alltheores:crafting/hammer/cinnabar/dust_from_gem",
    "alltheores:crafting/hammer/cinnabar/gem_from_ore",
    "alltheores:crafting/hammer/enderium/dust_from_ingot",
    "alltheores:crafting/hammer/iridium/dust_from_ingot",
    "alltheores:crafting/hammer/iridium/dust_from_ore",
    "alltheores:crafting/hammer/iridium/dust_from_raw",
    "alltheores:crafting/hammer/lumium/dust_from_ingot",
    "alltheores:crafting/hammer/peridot/dust_from_gem",
    "alltheores:crafting/hammer/peridot/gem_from_ore",
    "alltheores:crafting/hammer/platinum/dust_from_ingot",
    "alltheores:crafting/hammer/platinum/dust_from_ore",
    "alltheores:crafting/hammer/platinum/dust_from_raw",
    "alltheores:crafting/hammer/ruby/dust_from_gem",
    "alltheores:crafting/hammer/ruby/gem_from_ore",
    "alltheores:crafting/hammer/sapphire/dust_from_gem",
    "alltheores:crafting/hammer/sapphire/gem_from_ore",
    "alltheores:crafting/hammer/signalum/dust_from_ingot",
    "alltheores:crafting/iridium/block_from_ingot",
    "alltheores:crafting/iridium/gear",
    "alltheores:crafting/iridium/ingot_from_block",
    "alltheores:crafting/iridium/ingot_from_nugget",
    "alltheores:crafting/iridium/nugget_from_ingot",
    "alltheores:crafting/iridium/plate",
    "alltheores:crafting/iridium/raw_block_from_raw",
    "alltheores:crafting/iridium/raw_from_raw_block",
    "alltheores:crafting/iridium/rod",
    "alltheores:crafting/lumium/alloy_blending_from_dust",
    "alltheores:crafting/lumium/block_from_ingot",
    "alltheores:crafting/lumium/gear",
    "alltheores:crafting/lumium/ingot_from_block",
    "alltheores:crafting/lumium/ingot_from_nugget",
    "alltheores:crafting/lumium/nugget_from_ingot",
    "alltheores:crafting/lumium/plate",
    "alltheores:crafting/lumium/rod",
    "alltheores:crafting/peridot/block_from_gem",
    "alltheores:crafting/peridot/gem_from_block",
    "alltheores:crafting/platinum/block_from_ingot",
    "alltheores:crafting/platinum/gear",
    "alltheores:crafting/platinum/ingot_from_block",
    "alltheores:crafting/platinum/ingot_from_nugget",
    "alltheores:crafting/platinum/nugget_from_ingot",
    "alltheores:crafting/platinum/plate",
    "alltheores:crafting/platinum/raw_block_from_raw",
    "alltheores:crafting/platinum/raw_from_raw_block",
    "alltheores:crafting/platinum/rod",
    "alltheores:crafting/ruby/block_from_gem",
    "alltheores:crafting/ruby/gem_from_block",
    "alltheores:crafting/sapphire/block_from_gem",
    "alltheores:crafting/sapphire/gem_from_block",
    "alltheores:crafting/signalum/alloy_blending_from_dust",
    "alltheores:crafting/signalum/block_from_ingot",
    "alltheores:crafting/signalum/gear",
    "alltheores:crafting/signalum/ingot_from_block",
    "alltheores:crafting/signalum/ingot_from_nugget",
    "alltheores:crafting/signalum/nugget_from_ingot",
    "alltheores:crafting/signalum/plate",
    "alltheores:crafting/signalum/rod",
    "alltheores:crusher/cinnabar/from_gem",
    "alltheores:crusher/cinnabar/from_ore",
    "alltheores:crusher/enderium/from_ingot",
    "alltheores:crusher/iridium/from_ingot",
    "alltheores:crusher/iridium/from_ore",
    "alltheores:crusher/iridium/from_raw",
    "alltheores:crusher/iridium/from_raw_block",
    "alltheores:crusher/lumium/from_ingot",
    "alltheores:crusher/peridot/from_gem",
    "alltheores:crusher/peridot/from_ore",
    "alltheores:crusher/platinum/from_ingot",
    "alltheores:crusher/platinum/from_ore",
    "alltheores:crusher/platinum/from_raw",
    "alltheores:crusher/platinum/from_raw_block",
    "alltheores:crusher/ruby/from_gem",
    "alltheores:crusher/ruby/from_ore",
    "alltheores:crusher/sapphire/from_gem",
    "alltheores:crusher/sapphire/from_ore",
    "alltheores:crusher/signalum/from_ingot",
    "alltheores:crushing/cinnabar/from_gem",
    "alltheores:crushing/cinnabar/from_ore",
    "alltheores:crushing/enderium/from_dust",
    "alltheores:crushing/iridium/from_dust",
    "alltheores:crushing/iridium/from_ore",
    "alltheores:crushing/iridium/from_raw",
    "alltheores:crushing/iridium/from_raw_block",
    "alltheores:crushing/lumium/from_dust",
    "alltheores:crushing/peridot/from_gem",
    "alltheores:crushing/peridot/from_ore",
    "alltheores:crushing/platinum/from_dust",
    "alltheores:crushing/platinum/from_ore",
    "alltheores:crushing/platinum/from_raw",
    "alltheores:crushing/platinum/from_raw_block",
    "alltheores:crushing/ruby/from_gem",
    "alltheores:crushing/ruby/from_ore",
    "alltheores:crushing/sapphire/from_gem",
    "alltheores:crushing/sapphire/from_ore",
    "alltheores:crushing/signalum/from_dust",
    "alltheores:metalpress/enderium/gear",
    "alltheores:metalpress/enderium/plate",
    "alltheores:metalpress/enderium/rod",
    "alltheores:metalpress/iridium/gear",
    "alltheores:metalpress/iridium/plate",
    "alltheores:metalpress/iridium/rod",
    "alltheores:metalpress/lumium/gear",
    "alltheores:metalpress/lumium/plate",
    "alltheores:metalpress/lumium/rod",
    "alltheores:metalpress/platinum/gear",
    "alltheores:metalpress/platinum/plate",
    "alltheores:metalpress/platinum/rod",
    "alltheores:metalpress/signalum/gear",
    "alltheores:metalpress/signalum/plate",
    "alltheores:metalpress/signalum/rod",
    "alltheores:platinum_ore_hammer",
    "alltheores:processing/cinnabar/dust/from_gem",
    "alltheores:processing/cinnabar/dust/from_ore",
    "alltheores:processing/cinnabar/from_dust",
    "alltheores:processing/enderium/dust/from_ingot",
    "alltheores:processing/iridium/clump/from_ore",
    "alltheores:processing/iridium/clump/from_raw",
    "alltheores:processing/iridium/clump/from_raw_block",
    "alltheores:processing/iridium/clump/from_shard",
    "alltheores:processing/iridium/crystal/from_slurry",
    "alltheores:processing/iridium/dirty_dust/from_clump",
    "alltheores:processing/iridium/dust/from_dirty_dust",
    "alltheores:processing/iridium/dust/from_ingot",
    "alltheores:processing/iridium/dust/from_ore",
    "alltheores:processing/iridium/dust/from_raw",
    "alltheores:processing/iridium/dust/from_raw_block",
    "alltheores:processing/iridium/shard/from_crystal",
    "alltheores:processing/iridium/shard/from_ore",
    "alltheores:processing/iridium/shard/from_raw",
    "alltheores:processing/iridium/shard/from_raw_block",
    "alltheores:processing/iridium/slurry/dirty/from_ore",
    "alltheores:processing/iridium/slurry/dirty/from_raw",
    "alltheores:processing/lumium/dust/from_ingot",
    "alltheores:processing/peridot/dust/from_gem",
    "alltheores:processing/peridot/dust/from_ore",
    "alltheores:processing/peridot/from_dust",
    "alltheores:processing/platinum/clump/from_ore",
    "alltheores:processing/platinum/clump/from_raw",
    "alltheores:processing/platinum/clump/from_raw_block",
    "alltheores:processing/platinum/clump/from_shard",
    "alltheores:processing/platinum/crystal/from_slurry",
    "alltheores:processing/platinum/dirty_dust/from_clump",
    "alltheores:processing/platinum/dust/from_dirty_dust",
    "alltheores:processing/platinum/dust/from_ingot",
    "alltheores:processing/platinum/dust/from_ore",
    "alltheores:processing/platinum/dust/from_raw",
    "alltheores:processing/platinum/dust/from_raw_block",
    "alltheores:processing/platinum/shard/from_crystal",
    "alltheores:processing/platinum/shard/from_ore",
    "alltheores:processing/platinum/shard/from_raw",
    "alltheores:processing/platinum/shard/from_raw_block",
    "alltheores:processing/platinum/slurry/dirty/from_ore",
    "alltheores:processing/platinum/slurry/dirty/from_raw",
    "alltheores:processing/ruby/dust/from_gem",
    "alltheores:processing/ruby/dust/from_ore",
    "alltheores:processing/ruby/from_dust",
    "alltheores:processing/sapphire/dust/from_gem",
    "alltheores:processing/sapphire/dust/from_ore",
    "alltheores:processing/sapphire/from_dust",
    "alltheores:processing/signalum/dust/from_ingot",
    "alltheores:sag_milling/cinnabar/gem",
    "alltheores:sag_milling/cinnabar/ore",
    "alltheores:sag_milling/enderium/ingot",
    "alltheores:sag_milling/iridium/ingot",
    "alltheores:sag_milling/iridium/ore",
    "alltheores:sag_milling/iridium/raw",
    "alltheores:sag_milling/lumium/ingot",
    "alltheores:sag_milling/peridot/gem",
    "alltheores:sag_milling/peridot/ore",
    "alltheores:sag_milling/platinum/ingot",
    "alltheores:sag_milling/platinum/ore",
    "alltheores:sag_milling/platinum/raw",
    "alltheores:sag_milling/ruby/gem",
    "alltheores:sag_milling/ruby/ore",
    "alltheores:sag_milling/sapphire/gem",
    "alltheores:sag_milling/sapphire/ore",
    "alltheores:sag_milling/signalum/ingot",
    "alltheores:smelting/enderium/dust_blasting",
    "alltheores:smelting/enderium/dust_smelting",
    "alltheores:smelting/iridium/dust_blasting",
    "alltheores:smelting/iridium/dust_smelting",
    "alltheores:smelting/iridium/ore_blasting",
    "alltheores:smelting/iridium/ore_smelting",
    "alltheores:smelting/iridium/raw_blasting",
    "alltheores:smelting/iridium/raw_block_blasting",
    "alltheores:smelting/iridium/raw_block_smelting",
    "alltheores:smelting/iridium/raw_smelting",
    "alltheores:smelting/lumium/dust_blasting",
    "alltheores:smelting/lumium/dust_smelting",
    "alltheores:smelting/platinum/dust_blasting",
    "alltheores:smelting/platinum/dust_smelting",
    "alltheores:smelting/platinum/ore_blasting",
    "alltheores:smelting/platinum/ore_smelting",
    "alltheores:smelting/platinum/raw_blasting",
    "alltheores:smelting/platinum/raw_block_blasting",
    "alltheores:smelting/platinum/raw_block_smelting",
    "alltheores:smelting/platinum/raw_smelting",
    "alltheores:smelting/signalum/dust_blasting",
    "alltheores:smelting/signalum/dust_smelting",
    "create:crushing/platinum_ore",
    "create:crushing/raw_platinum",
    "immersiveengineering:arcfurnace/dust_platinum",
    "immersiveengineering:arcfurnace/ore_platinum",
    "immersiveengineering:arcfurnace/raw_block_platinum",
    "immersiveengineering:arcfurnace/raw_ore_platinum",
    "immersiveengineering:crafting/hammercrushing_platinum",
    "immersiveengineering:crafting/raw_hammercrushing_platinum",
    "immersiveengineering:crusher/ingot_platinum",
    "immersiveengineering:crusher/ore_platinum",
    "immersiveengineering:crusher/raw_block_platinum",
    "immersiveengineering:crusher/raw_ore_platinum",
    "immersiveengineering:metalpress/gear_platinum",
    "immersiveengineering:metalpress/plate_platinum",
    "immersiveengineering:metalpress/rod_platinum",
    "immersiveengineering:metalpress/wire_platinum",
    "industrialforegoing:laser_drill_ore/ores/cinnabar",
    "industrialforegoing:laser_drill_ore/ores/peridot",
    "industrialforegoing:laser_drill_ore/ores/ruby",
    "industrialforegoing:laser_drill_ore/ores/sapphire",
    "industrialforegoing:laser_drill_ore/raw_materials/cinnabar",
    "industrialforegoing:laser_drill_ore/raw_materials/iridium",
    "industrialforegoing:laser_drill_ore/raw_materials/platinum",
    "integrateddynamics:mechanical_squeezer/ore/raw_platinum",
    "integrateddynamics:squeezer/ore/raw_platinum",
    "mysticalagriculture:essence/common/iridium_ingot",
    "mysticalagriculture:essence/common/platinum_ingot",
    "mysticalagriculture:essence/gems/peridot",
    "mysticalagriculture:essence/gems/ruby",
    "mysticalagriculture:essence/gems/sapphire",
    "mysticalagriculture:essence/thermal/enderium_ingot",
    "mysticalagriculture:essence/thermal/lumium_ingot",
    "mysticalagriculture:essence/thermal/signalum_ingot",
    "mysticalagriculture:seed/crafting/enderium",
    "mysticalagriculture:seed/crafting/iridium",
    "mysticalagriculture:seed/crafting/lumium",
    "mysticalagriculture:seed/crafting/peridot",
    "mysticalagriculture:seed/crafting/platinum",
    "mysticalagriculture:seed/crafting/ruby",
    "mysticalagriculture:seed/crafting/sapphire",
    "mysticalagriculture:seed/crafting/signalum",
    "mysticalagriculture:seed/infusion/enderium",
    "mysticalagriculture:seed/infusion/iridium",
    "mysticalagriculture:seed/infusion/lumium",
    "mysticalagriculture:seed/infusion/peridot",
    "mysticalagriculture:seed/infusion/platinum",
    "mysticalagriculture:seed/infusion/ruby",
    "mysticalagriculture:seed/infusion/sapphire",
    "mysticalagriculture:seed/infusion/signalum",
    "occultism:crushing/cinnabar_dust_from_gem",
    "occultism:crushing/cinnabar_dust_from_ore",
    "occultism:crushing/enderium_dust_from_ingot",
    "occultism:crushing/iridium_dirty_dust_from_clump",
    "occultism:crushing/iridium_dust_from_ingot",
    "occultism:crushing/iridium_dust_from_ore",
    "occultism:crushing/iridium_dust_from_raw",
    "occultism:crushing/iridium_dust_from_raw_block",
    "occultism:crushing/lumium_dust_from_ingot",
    "occultism:crushing/peridot_dust_from_gem",
    "occultism:crushing/peridot_dust_from_ore",
    "occultism:crushing/platinum_dirty_dust_from_clump",
    "occultism:crushing/platinum_dust_from_ingot",
    "occultism:crushing/platinum_dust_from_ore",
    "occultism:crushing/platinum_dust_from_raw",
    "occultism:crushing/platinum_dust_from_raw_block",
    "occultism:crushing/ruby_dust_from_gem",
    "occultism:crushing/ruby_dust_from_ore",
    "occultism:crushing/sapphire_dust_from_gem",
    "occultism:crushing/sapphire_dust_from_ore",
    "occultism:crushing/signalum_dust_from_ingot",
    "occultism:crystallize/cinnabar_from_dust",
    "occultism:crystallize/cinnabar_from_ore",
    "occultism:crystallize/peridot_from_dust",
    "occultism:crystallize/peridot_from_ore",
    "occultism:crystallize/ruby_from_dust",
    "occultism:crystallize/ruby_from_ore",
    "occultism:crystallize/sapphire_from_dust",
    "occultism:crystallize/sapphire_from_ore",
    "occultism:miner/eldritch/peridot",
    "occultism:miner/eldritch/ruby",
    "occultism:miner/eldritch/sapphire",
    "occultism:miner/ores/cinnabar_ore",
    "occultism:miner/ores/iridium_ore",
    "occultism:miner/ores/peridot_ore",
    "occultism:miner/ores/platinum_ore",
    "occultism:miner/ores/ruby_ore",
    "occultism:miner/ores/sapphire_ore",
    "productivebees:centrifuge/alloys/honeycomb_enderium",
    "productivebees:centrifuge/alloys/honeycomb_lumium",
    "productivebees:centrifuge/alloys/honeycomb_signalum",
    "productivebees:centrifuge/dusts/honeycomb_platinum",
    "productivebees:centrifuge/gems/honeycomb_cinnabar",
    "productivebees:centrifuge/gems/honeycomb_cinnabar_dust",
    "productivebees:centrifuge/gems/honeycomb_peridot",
    "productivebees:centrifuge/gems/honeycomb_ruby",
    "productivebees:centrifuge/gems/honeycomb_sapphire",
    "productivebees:centrifuge/raw_materials/honeycomb_iridium",
    "productivebees:centrifuge/raw_materials/honeycomb_platinum",
    "productivebees:ftbic/canning/iridium_bee",
    "replication:matter_values/c/tags/ingots/iridium",
    "replication:matter_values/c/tags/ingots/platinum",
    "alltheores:processing/platinum/slurry/dirty/from_raw_block",
    "alltheores:processing/iridium/slurry/dirty/from_raw_block"
]

// Fix the Create Steel pressing recipe
function fixCreateSteelPressing(event) {
    event.remove({ id: 'create:pressing/steel_ingot' })

    event.custom({
        type: 'create:pressing',
        ingredients: [
            {
                tag: 'c:ingots/steel'
            }
        ],
        results: [
            {
                id: 'alltheores:steel_plate'
            }
        ]
    }).id('create:pressing/steel_ingot')
}

// Dense uranium / yellorium cleanup
function cleanUpUraniumAndYellorium(event) {
    // scrap only gives dense uranium now
    const obsoleteAntarchyScrapRecipes = [
        'antarchy:uranium/raw_uranium_from_scrap',
        'antarchy:uranium/uranium_nugget_from_raw_uranium_scrap_smelting',
        'antarchy:uranium/uranium_nugget_from_raw_uranium_scrap_blasting'
    ]

    obsoleteAntarchyScrapRecipes.forEach(id => {
        event.remove({ id: id })
    })

    // these are the Antarchy recipes that actually need dense uranium
    const denseIngotRecipes = [
        'antarchy:gravity_gun',
        'antarchy:shrink_ray',

        'antarchy:ultimate/ultimate_axe',
        'antarchy:ultimate/ultimate_boots',
        'antarchy:ultimate/ultimate_bow',
        'antarchy:ultimate/ultimate_chestplate',
        'antarchy:ultimate/ultimate_crossbow',
        'antarchy:ultimate/ultimate_helmet',
        'antarchy:ultimate/ultimate_hoe',
        'antarchy:ultimate/ultimate_leggings',
        'antarchy:ultimate/ultimate_pickaxe',
        'antarchy:ultimate/ultimate_shovel',
        'antarchy:ultimate/ultimate_sword'
    ]

    denseIngotRecipes.forEach(id => {
        event.replaceInput(
            { id: id },
            'antarchy:uranium_ingot',
            'antarchy_ascension_companion:dense_uranium_ingot'
        )
    })

    event.replaceInput(
        { id: 'antarchy:attitude_adjuster' },
        'antarchy:uranium_block',
        'antarchy_ascension_companion:dense_uranium_block'
    )

    event.replaceInput(
        { id: 'antarchy:rainbow_sugar' },
        'antarchy:uranium_nugget',
        'antarchy_ascension_companion:dense_uranium_nugget'
    )

    // Extreme Reactors still hardcodes yellorium in these
    const fluidizerMachineRecipes = [
        'bigreactors:fluidizer/casing',
        'bigreactors:fluidizer/controller',
        'bigreactors:fluidizer/solidinjector'
    ]

    fluidizerMachineRecipes.forEach(id => {
        event.replaceInput(
            { id: id },
            '#c:ingots/yellorium',
            '#c:ingots/uranium'
        )
    })

    // remove the old solid yellorium recipes but the fluid stays
    const removedYelloriumRecipeIds = [
        // Extreme Reactors
        'bigreactors:blasting/yellorium_from_ore',
        'bigreactors:blasting/yellorium_from_raw',
        'bigreactors:smelting/yellorium_from_ore',
        'bigreactors:smelting/yellorium_from_raw',

        'bigreactors:crafting/raw_yellorium_component_to_storage',
        'bigreactors:crafting/raw_yellorium_storage_to_component',
        'bigreactors:crafting/yellorium_component_to_storage',
        'bigreactors:crafting/yellorium_storage_to_component',

        // reactor recipes that already have uranium versions
        'bigreactors:reactor/basic/controller_ingots_yellorium',
        'bigreactors:reactor/basic/fuelrod_ingots_yellorium',
        'bigreactors:reactor/reinforced/controller_ingots_yellorium',
        'bigreactors:reactor/reinforced/fuelrod_alt_ingots_yellorium',
        'bigreactors:reactor/reinforced/fuelrod_ingots_yellorium',

        'bigreactors:misc/book/erguide',

        // other mods that can still make yellorium
        'industrialforegoing:laser_drill_ore/ores/yellorite',
        'industrialforegoing:laser_drill_ore/raw_materials/yellorite',
        'industrialforegoing:laser_drill_ore/raw_materials/yellorium',
        'occultism:miner/eldritch/raw_yellorium',

        // yellorium crop stuff
        'mysticalagriculture:essence/extremereactors2/yellorium_ingot',
        'mysticalagriculture:seed/crafting/yellorium',
        'mysticalagriculture:seed/infusion/yellorium',
        'mysticalagriculture:seed/reprocessor/yellorium',
        'botanypots:mysticalagriculture/crop/yellorium_seeds',
        'mysticalengineering:cloche_yellorium_seed',
        'mekmm:compat/mysticalagriculture/yellorium',

        // old thermal compat
        'thermal:machine/pulverizer_yellorite_ore_to_dust',
        'thermal:machine/pulverizer_yellorium_ingot_to_dust'
    ]

    removedYelloriumRecipeIds.forEach(id => {
        event.remove({ id: id })
    })

    // catch anything else that still spits out one of the old items
    const removedSolidOutputs = [
        'bigreactors:yellorite_ore',
        'bigreactors:deepslate_yellorite_ore',
        'bigreactors:raw_yellorium',
        'bigreactors:raw_yellorium_block',
        'bigreactors:yellorium_ingot',
        'bigreactors:yellorium_block',
        'mysticalagriculture:yellorium_seeds',
        'mysticalagriculture:yellorium_essence'
    ]

    removedSolidOutputs.forEach(output => {
        event.remove({ output: output })
    })
}

// Removes Marvel titanium ore recipes
const removedMarvelTitaniumRecipes = [
    'occultism:miner/ores/titanium_ore',

    'marvel:titanium_ingot_from_smelting_titanium_ore',
    'marvel:titanium_ingot_from_smelting_deepslate_titanium_ore',
    'marvel:titanium_ingot_from_blasting_titanium_ore',
    'marvel:titanium_ingot_from_blasting_deepslate_titanium_ore'
]

// Removes unused Ice and Fire Sapphire stuff
const removedIceAndFireSapphireRecipes = [
    'iceandfire:sapphire_block_to_sapphire_gem',
    'iceandfire:sapphire_gem_to_sapphire_block',
    'iceandfire:furnace/sapphire',
    'iceandfire:furnace/sapphire_blasting'
]

// Removes Evolved Mekanism uranium ore processing recipes
const removedEvolvedMekanismUraniumRecipes = [
    'evolvedmekanism:processing/uranium/ore/depthrock_from_raw',
    'evolvedmekanism:processing/uranium/ore/end_stone_from_raw',
    'evolvedmekanism:processing/uranium/ore/holystone_from_raw',
    'evolvedmekanism:processing/uranium/ore/netherrack_from_raw',
    'evolvedmekanism:processing/uranium/ore/shiverstone_from_raw'
]

// Removes duplicate and unused ore processing (Ancient Stone silver/aluminum + AllTheOres iridium/platinum duplicates)
const antarchyDuplicateOreRecipeIds = [
    "alltheores:processing/iridium/slurry/from_dirty",
    "alltheores:processing/platinum/slurry/from_dirty",
    "iceandfire:furnace/deepslate_silver_ingot",
    "iceandfire:furnace/deepslate_silver_ingot_blasting",
    "iceandfire:furnace/silver_ingot",
    "iceandfire:furnace/silver_ingot_blasting",
    "iceandfire:raw_silver_block_to_raw_silver",
    "iceandfire:raw_silver_to_raw_silver_block",
    "iceandfire:silver_block_to_silver_ingot",
    "iceandfire:silver_ingot_from_blasting_raw_silver",
    "iceandfire:silver_ingot_from_smelting_raw_silver",
    "iceandfire:silver_ingot_to_silver_block",
    "iceandfire:silver_ingot_to_silver_nugget",
    "iceandfire:silver_nugget_to_silver_ingot",
    "mekmm:processing/silver/clump/from_ore",
    "mekmm:processing/silver/clump/from_raw_block",
    "mekmm:processing/silver/clump/from_raw_ore",
    "mekmm:processing/silver/clump/from_shard",
    "mekmm:processing/silver/crystal/from_slurry",
    "mekmm:processing/silver/dirty_dust/from_clump",
    "mekmm:processing/silver/dust/from_dirty_dust",
    "mekmm:processing/silver/dust/from_ingot",
    "mekmm:processing/silver/dust/from_ore",
    "mekmm:processing/silver/dust/from_raw_block",
    "mekmm:processing/silver/dust/from_raw_ore",
    "mekmm:processing/silver/ingot/from_block",
    "mekmm:processing/silver/ingot/from_dust_blasting",
    "mekmm:processing/silver/ingot/from_dust_smelting",
    "mekmm:processing/silver/ingot/from_nuggets",
    "mekmm:processing/silver/ingot/from_ore_blasting",
    "mekmm:processing/silver/ingot/from_ore_smelting",
    "mekmm:processing/silver/ingot/from_raw_blasting",
    "mekmm:processing/silver/ingot/from_raw_smelting",
    "mekmm:processing/silver/nugget/from_ingot",
    "mekmm:processing/silver/ore/deepslate_from_raw",
    "mekmm:processing/silver/ore/from_raw",
    "mekmm:processing/silver/raw_storage_blocks/from_raw",
    "mekmm:processing/silver/raw/from_raw_block",
    "mekmm:processing/silver/shard/from_crystal",
    "mekmm:processing/silver/shard/from_ore",
    "mekmm:processing/silver/shard/from_raw_block",
    "mekmm:processing/silver/shard/from_raw_ore",
    "mekmm:processing/silver/slurry/clean",
    "mekmm:processing/silver/slurry/dirty/from_ore",
    "mekmm:processing/silver/slurry/dirty/from_raw_block",
    "mekmm:processing/silver/slurry/dirty/from_raw_ore",
    "mekmm:processing/silver/storage_blocks/from_ingots",
    "xycraft_machines:compat/mek/processing/aluminum/clump/from_ore",
    "xycraft_machines:compat/mek/processing/aluminum/clump/from_raw_block",
    "xycraft_machines:compat/mek/processing/aluminum/clump/from_raw_ore",
    "xycraft_machines:compat/mek/processing/aluminum/clump/from_shard",
    "xycraft_machines:compat/mek/processing/aluminum/crystal/from_slurry",
    "xycraft_machines:compat/mek/processing/aluminum/dirty_dust/from_clump",
    "xycraft_machines:compat/mek/processing/aluminum/dust/from_dirty_dust",
    "xycraft_machines:compat/mek/processing/aluminum/dust/from_ingot",
    "xycraft_machines:compat/mek/processing/aluminum/dust/from_ore",
    "xycraft_machines:compat/mek/processing/aluminum/dust/from_raw_block",
    "xycraft_machines:compat/mek/processing/aluminum/dust/from_raw_ore",
    "xycraft_machines:compat/mek/processing/aluminum/ingot/from_dust_blasting",
    "xycraft_machines:compat/mek/processing/aluminum/ingot/from_dust_smelting",
    "xycraft_machines:compat/mek/processing/aluminum/ore/deepslate_from_raw",
    "xycraft_machines:compat/mek/processing/aluminum/ore/from_raw",
    "xycraft_machines:compat/mek/processing/aluminum/shard/from_crystal",
    "xycraft_machines:compat/mek/processing/aluminum/shard/from_ore",
    "xycraft_machines:compat/mek/processing/aluminum/shard/from_raw_block",
    "xycraft_machines:compat/mek/processing/aluminum/shard/from_raw_ore",
    "xycraft_machines:compat/mek/processing/aluminum/slurry/clean",
    "xycraft_machines:compat/mek/processing/aluminum/slurry/dirty/from_ore",
    "xycraft_machines:compat/mek/processing/aluminum/slurry/dirty/from_raw_block",
    "xycraft_machines:compat/mek/processing/aluminum/slurry/dirty/from_raw_ore"
]

// Removes unused Productive Bees, Mystical Agriculture and AllTheCompressed recipes
// (1x AllTheCompressed variants and common/gems/thermal essence + crafting/infusion seeds are already
// removed above via removedAllTheOresRecipes; only the non-duplicate entries remain here.)
const removedMaterialIntegrationRecipes = [
    "allthecompressed:compress/cinnabar_block_2x",
    "allthecompressed:compress/cinnabar_block_3x",
    "allthecompressed:compress/cinnabar_block_4x",
    "allthecompressed:compress/cinnabar_block_5x",
    "allthecompressed:compress/cinnabar_block_6x",
    "allthecompressed:compress/cinnabar_block_7x",
    "allthecompressed:compress/cinnabar_block_8x",
    "allthecompressed:compress/cinnabar_block_9x",
    "allthecompressed:compress/enderium_block_2x",
    "allthecompressed:compress/enderium_block_3x",
    "allthecompressed:compress/enderium_block_4x",
    "allthecompressed:compress/enderium_block_5x",
    "allthecompressed:compress/enderium_block_6x",
    "allthecompressed:compress/enderium_block_7x",
    "allthecompressed:compress/enderium_block_8x",
    "allthecompressed:compress/enderium_block_9x",
    "allthecompressed:compress/iridium_block_2x",
    "allthecompressed:compress/iridium_block_3x",
    "allthecompressed:compress/iridium_block_4x",
    "allthecompressed:compress/iridium_block_5x",
    "allthecompressed:compress/iridium_block_6x",
    "allthecompressed:compress/iridium_block_7x",
    "allthecompressed:compress/iridium_block_8x",
    "allthecompressed:compress/iridium_block_9x",
    "allthecompressed:compress/lumium_block_2x",
    "allthecompressed:compress/lumium_block_3x",
    "allthecompressed:compress/lumium_block_4x",
    "allthecompressed:compress/lumium_block_5x",
    "allthecompressed:compress/lumium_block_6x",
    "allthecompressed:compress/lumium_block_7x",
    "allthecompressed:compress/lumium_block_8x",
    "allthecompressed:compress/lumium_block_9x",
    "allthecompressed:compress/peridot_block_2x",
    "allthecompressed:compress/peridot_block_3x",
    "allthecompressed:compress/peridot_block_4x",
    "allthecompressed:compress/peridot_block_5x",
    "allthecompressed:compress/peridot_block_6x",
    "allthecompressed:compress/peridot_block_7x",
    "allthecompressed:compress/peridot_block_8x",
    "allthecompressed:compress/peridot_block_9x",
    "allthecompressed:compress/platinum_block_2x",
    "allthecompressed:compress/platinum_block_3x",
    "allthecompressed:compress/platinum_block_4x",
    "allthecompressed:compress/platinum_block_5x",
    "allthecompressed:compress/platinum_block_6x",
    "allthecompressed:compress/platinum_block_7x",
    "allthecompressed:compress/platinum_block_8x",
    "allthecompressed:compress/platinum_block_9x",
    "allthecompressed:compress/raw_iridium_block_2x",
    "allthecompressed:compress/raw_iridium_block_3x",
    "allthecompressed:compress/raw_iridium_block_4x",
    "allthecompressed:compress/raw_iridium_block_5x",
    "allthecompressed:compress/raw_iridium_block_6x",
    "allthecompressed:compress/raw_iridium_block_7x",
    "allthecompressed:compress/raw_iridium_block_8x",
    "allthecompressed:compress/raw_iridium_block_9x",
    "allthecompressed:compress/raw_platinum_block_2x",
    "allthecompressed:compress/raw_platinum_block_3x",
    "allthecompressed:compress/raw_platinum_block_4x",
    "allthecompressed:compress/raw_platinum_block_5x",
    "allthecompressed:compress/raw_platinum_block_6x",
    "allthecompressed:compress/raw_platinum_block_7x",
    "allthecompressed:compress/raw_platinum_block_8x",
    "allthecompressed:compress/raw_platinum_block_9x",
    "allthecompressed:compress/ruby_block_2x",
    "allthecompressed:compress/ruby_block_3x",
    "allthecompressed:compress/ruby_block_4x",
    "allthecompressed:compress/ruby_block_5x",
    "allthecompressed:compress/ruby_block_6x",
    "allthecompressed:compress/ruby_block_7x",
    "allthecompressed:compress/ruby_block_8x",
    "allthecompressed:compress/ruby_block_9x",
    "allthecompressed:compress/sapphire_block_2x",
    "allthecompressed:compress/sapphire_block_3x",
    "allthecompressed:compress/sapphire_block_4x",
    "allthecompressed:compress/sapphire_block_5x",
    "allthecompressed:compress/sapphire_block_6x",
    "allthecompressed:compress/sapphire_block_7x",
    "allthecompressed:compress/sapphire_block_8x",
    "allthecompressed:compress/sapphire_block_9x",
    "allthecompressed:compress/signalum_block_2x",
    "allthecompressed:compress/signalum_block_3x",
    "allthecompressed:compress/signalum_block_4x",
    "allthecompressed:compress/signalum_block_5x",
    "allthecompressed:compress/signalum_block_6x",
    "allthecompressed:compress/signalum_block_7x",
    "allthecompressed:compress/signalum_block_8x",
    "allthecompressed:compress/signalum_block_9x",
    "allthecompressed:decompress/cinnabar_block_2x",
    "allthecompressed:decompress/cinnabar_block_3x",
    "allthecompressed:decompress/cinnabar_block_4x",
    "allthecompressed:decompress/cinnabar_block_5x",
    "allthecompressed:decompress/cinnabar_block_6x",
    "allthecompressed:decompress/cinnabar_block_7x",
    "allthecompressed:decompress/cinnabar_block_8x",
    "allthecompressed:decompress/cinnabar_block_9x",
    "allthecompressed:decompress/enderium_block_2x",
    "allthecompressed:decompress/enderium_block_3x",
    "allthecompressed:decompress/enderium_block_4x",
    "allthecompressed:decompress/enderium_block_5x",
    "allthecompressed:decompress/enderium_block_6x",
    "allthecompressed:decompress/enderium_block_7x",
    "allthecompressed:decompress/enderium_block_8x",
    "allthecompressed:decompress/enderium_block_9x",
    "allthecompressed:decompress/iridium_block_2x",
    "allthecompressed:decompress/iridium_block_3x",
    "allthecompressed:decompress/iridium_block_4x",
    "allthecompressed:decompress/iridium_block_5x",
    "allthecompressed:decompress/iridium_block_6x",
    "allthecompressed:decompress/iridium_block_7x",
    "allthecompressed:decompress/iridium_block_8x",
    "allthecompressed:decompress/iridium_block_9x",
    "allthecompressed:decompress/lumium_block_2x",
    "allthecompressed:decompress/lumium_block_3x",
    "allthecompressed:decompress/lumium_block_4x",
    "allthecompressed:decompress/lumium_block_5x",
    "allthecompressed:decompress/lumium_block_6x",
    "allthecompressed:decompress/lumium_block_7x",
    "allthecompressed:decompress/lumium_block_8x",
    "allthecompressed:decompress/lumium_block_9x",
    "allthecompressed:decompress/peridot_block_2x",
    "allthecompressed:decompress/peridot_block_3x",
    "allthecompressed:decompress/peridot_block_4x",
    "allthecompressed:decompress/peridot_block_5x",
    "allthecompressed:decompress/peridot_block_6x",
    "allthecompressed:decompress/peridot_block_7x",
    "allthecompressed:decompress/peridot_block_8x",
    "allthecompressed:decompress/peridot_block_9x",
    "allthecompressed:decompress/platinum_block_2x",
    "allthecompressed:decompress/platinum_block_3x",
    "allthecompressed:decompress/platinum_block_4x",
    "allthecompressed:decompress/platinum_block_5x",
    "allthecompressed:decompress/platinum_block_6x",
    "allthecompressed:decompress/platinum_block_7x",
    "allthecompressed:decompress/platinum_block_8x",
    "allthecompressed:decompress/platinum_block_9x",
    "allthecompressed:decompress/raw_iridium_block_2x",
    "allthecompressed:decompress/raw_iridium_block_3x",
    "allthecompressed:decompress/raw_iridium_block_4x",
    "allthecompressed:decompress/raw_iridium_block_5x",
    "allthecompressed:decompress/raw_iridium_block_6x",
    "allthecompressed:decompress/raw_iridium_block_7x",
    "allthecompressed:decompress/raw_iridium_block_8x",
    "allthecompressed:decompress/raw_iridium_block_9x",
    "allthecompressed:decompress/raw_platinum_block_2x",
    "allthecompressed:decompress/raw_platinum_block_3x",
    "allthecompressed:decompress/raw_platinum_block_4x",
    "allthecompressed:decompress/raw_platinum_block_5x",
    "allthecompressed:decompress/raw_platinum_block_6x",
    "allthecompressed:decompress/raw_platinum_block_7x",
    "allthecompressed:decompress/raw_platinum_block_8x",
    "allthecompressed:decompress/raw_platinum_block_9x",
    "allthecompressed:decompress/ruby_block_2x",
    "allthecompressed:decompress/ruby_block_3x",
    "allthecompressed:decompress/ruby_block_4x",
    "allthecompressed:decompress/ruby_block_5x",
    "allthecompressed:decompress/ruby_block_6x",
    "allthecompressed:decompress/ruby_block_7x",
    "allthecompressed:decompress/ruby_block_8x",
    "allthecompressed:decompress/ruby_block_9x",
    "allthecompressed:decompress/sapphire_block_2x",
    "allthecompressed:decompress/sapphire_block_3x",
    "allthecompressed:decompress/sapphire_block_4x",
    "allthecompressed:decompress/sapphire_block_5x",
    "allthecompressed:decompress/sapphire_block_6x",
    "allthecompressed:decompress/sapphire_block_7x",
    "allthecompressed:decompress/sapphire_block_8x",
    "allthecompressed:decompress/sapphire_block_9x",
    "allthecompressed:decompress/signalum_block_2x",
    "allthecompressed:decompress/signalum_block_3x",
    "allthecompressed:decompress/signalum_block_4x",
    "allthecompressed:decompress/signalum_block_5x",
    "allthecompressed:decompress/signalum_block_6x",
    "allthecompressed:decompress/signalum_block_7x",
    "allthecompressed:decompress/signalum_block_8x",
    "allthecompressed:decompress/signalum_block_9x",
    "mysticalagriculture:seed/reprocessor/enderium",
    "mysticalagriculture:seed/reprocessor/iridium",
    "mysticalagriculture:seed/reprocessor/lumium",
    "mysticalagriculture:seed/reprocessor/peridot",
    "mysticalagriculture:seed/reprocessor/platinum",
    "mysticalagriculture:seed/reprocessor/ruby",
    "mysticalagriculture:seed/reprocessor/sapphire",
    "mysticalagriculture:seed/reprocessor/signalum",
    "productivebees:bee_breeding/alloys/enderium_bee",
    "productivebees:bee_breeding/alloys/enderium_bee_platinum",
    "productivebees:bee_breeding/alloys/lumium_bee",
    "productivebees:bee_breeding/alloys/signalum_bee",
    "productivebees:bee_breeding/gems/cinnabar_bee",
    "productivebees:bee_breeding/raw_materials/iridium_bee",
    "productivebees:bee_breeding/raw_materials/platinum_bee",
    "productivebees:bee_conversion/gems/green_sapphire_bee",
    "productivebees:bee_conversion/gems/peridot_bee",
    "productivebees:bee_conversion/gems/ruby_bee",
    "productivebees:bee_conversion/gems/sapphire_bee",
    "productivebees:bee_produce/alloys/enderium_bee",
    "productivebees:bee_produce/alloys/lumium_bee",
    "productivebees:bee_produce/alloys/signalum_bee",
    "productivebees:bee_produce/gems/cinnabar_bee",
    "productivebees:bee_produce/gems/green_sapphire_bee",
    "productivebees:bee_produce/gems/peridot_bee",
    "productivebees:bee_produce/gems/ruby_bee",
    "productivebees:bee_produce/gems/sapphire_bee",
    "productivebees:bee_produce/raw_materials/iridium_bee",
    "productivebees:bee_produce/raw_materials/platinum_bee",
    "productivebees:centrifuge/gems/honeycomb_green_sapphire"
]

ServerEvents.recipes(event => {
    removedAllTheOresRecipes.forEach(id => {
        event.remove({ id: id })
    })

    fixCreateSteelPressing(event)

    event.remove({ id: 'create:pressing/compat/immersiveengineering/plate_steel' })

    cleanUpUraniumAndYellorium(event)

    removedMarvelTitaniumRecipes.forEach(id => {
        event.remove({ id: id })
    })

    removedIceAndFireSapphireRecipes.forEach(id => {
        event.remove({ id: id })
    })

    removedEvolvedMekanismUraniumRecipes.forEach(id => {
        event.remove({ id: id })
    })

    antarchyDuplicateOreRecipeIds.forEach(id => {
        event.remove({ id: id })
    })

    removedMaterialIntegrationRecipes.forEach(id => {
        event.remove({ id: id })
    })
})

// KubeJS Studio Recipes
ServerEvents.generateData('after_mods', event => {
    event.json('tiab:recipe/time_in_a_bottle', {"type":"minecraft:crafting_shaped","pattern":["###","ABA","CDC"],"key":{"#":{"tag":"c:ingots/gold"},"A":{"tag":"c:gems/diamond"},"B":{"item":"gag:time_sand_pouch"},"C":{"tag":"c:gems/lapis"},"D":{"item":"minecraft:glass_bottle"}},"result":{"id":"tiab:time_in_a_bottle","count":1}})
})