version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
mcwfences = true
farmersdelight = true
create_new_age = true
cookingforblockheads = true
antarchy_ascension_companion = true
laserbridges = true
aether_beyond_parity = true
ae2ltpp = true
mcwstairs = true
copycats = true
gobberdelight = true
integratedterminals = true
comforts = true
advanced_ae = true
allthecompressed = true
alltheores = true
aether = true
prefab = true
the_bumblezone = true
lucky = true
ftbquests = true
functionalstorage = true
extendedcrafting = true
evolvedmekanism = true
twilight_forest_final_boss = true
apotheosis = true
ars_zero = true
appliedcooking = true
rftoolsbase = true
ae2lt = true
create = true
yungscavebiomes = true
buildinggadgets2 = true
sfm = true
easy_villagers = true
anvilcore = true
mcwfurnitures = true
expanded_combat = true
sophisticatedstorage = true
aquaculturedelight = true
immeng = true
sliceanddice = true
waystones = true
apothic_enchanting = true
appliedpneumatics = true
camol = true
pipez = true
disenchanting_table = true
secretroomsmod = true
framedblocks = true
megacells = true
xycraft_machines = true
createstockbridge = true
integratedscripting = true
create_optical = true
hostilenetworks = true
igleelib = true
quark = true
mcwquark = true
irons_spellbooks = true
dndecor = true
gobber2 = true
createutilities = true
chancecubes = true
create_sa = true
mcwlights = true
modularbees = true
marvel = true
pneumaticcraft = true
mcwdoors = true
little_big_redstone = true
mekanism = true
inventorypets = true
interiors = true
appliedsoul = true
deep_aether = true
utilitarian = true
trashcans = true
ae2cs = true
ars_ocultas = true
create_dragons_plus = true
ars_additions = true
merequester = true
mininggadgets = true
ae2 = true
draconicevolution = true
ars_nouveau = true
irons_patreon_lib = true
productivebees = true
cfm_wap = true
mekmm = true
javd = true
fluxnetworks = true
compactmachines = true
mutantmonsters = true
create_mechanical_extruder = true
integratedtunnels = true
mffs = true
createtransmission = true
tflostblocks = true
potionsmaster = true
laserio = true
aether_enhanced_extinguishing = true
refurbished_furniture = true
actuallyadditions = true
evilcraft = true
powah = true
appliedcreate = true
ars_technica = true
mcwbridges = true
entangled = true
railways = true
antarchy = true
aether_treasure_reforging = true
handcrafted = true
applied_extended_crafting = true
apprep = true
botanypotstiers = true
wirelesschargers = true
ars_creo = true
dndesires = true
infinity = true
supplementaries = true
replication = true
create_vibrant_vaults = true
aether_ores = true
twilight_lootr = true
industrialforegoing = true
endrem = true
createenchantablemachinery = true
rftoolsbuilder = true
minecraft = true
railcraft = true
occultism = true
create_connected = true
integratedmekanism = true
undergarden = true
occultengineering = true
createaddition = true
twilightforest = true
jdttimeaccelerators = true
createframed = true
enderstorage = true
gag = true
easy_piglins = true
energymeter = true
industrialforegoingsouls = true
ironfurnaces = true
bigreactors = true
immersiveengineering = true
create_aquatic_ambitions = true
sizeable_foliage = true
integratedcrafting = true
eternal_starlight = true
mcwroofs = true
itemcollectors = true
mysticalagradditions = true
pylons = true
mcwwindows = true
xycraft_override = true
me_beam_former = true
endersourcejars = true
tf_dnv = true
storagedelight = true
securitycraft = true
more_pylons = true
cataclysm = true
starbunclemania = true
ae2omnicells = true
mysticalagriculture = true
routers = true
create_enchantment_industry = true
mcwpaths = true
createdieselgenerators = true
expandedae = true
farmingforblockheads = true
simplylight = true
xycraft_world = true
botanypots = true
bellsandwhistles = true
mcwtrpdoors = true
mekanismgenerators = true
actuallyadditionsaddon = true
amendments = true
moonlight = true
integrateddynamics = true
sophisticatedbackpacks = true
appflux = true
torchmaster = true
resource_nether_ores = true
sawmill = true
createcasing = true
aquaculture = true
justdirethings = true
modularrouters = true
irons_lib = true
lootr = true
createdeco = true
iceandfire = true
elevatorid = true
regions_unexplored = true
create_better_motors = true
ars_elemental = true
tempad = true
sauce = true
forbidden_arcanus = true
extendedae = true
ad_astra = true
ad_astra_giselle_addon = true
mcwregionsunexplored = true
